<a href="https://colab.research.google.com/github/kxrrym03/Fake-News-Detection/blob/main/Fake_News_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
from google.colab import files
uploaded = files.upload()

Saving news_dataset.csv to news_dataset.csv

In [4]:
df = pd.read_csv('news_dataset.csv')
df.shape

(6000, 5)

In [5]:
df.head()

,title,text,subject,date,label
0,WATCH: Trump Just Told All The Anti-Gay Bigot...,A whole lot of evangelical Trump voters just d...,News,"November 13, 2016",0
1,"China backs U.N. call for justice in Yemen, U....",GENEVA (Reuters) - China signaled on Wednesday...,worldnews,"September 13, 2017",1
2,THE PEOPLE’S PRESIDENT: Trump Meets With Coal ...,,politics,"Feb 16, 2017",0
3,WSJ REPORTER RIPS INTO DEM CANDIDATES For Thei...,THE WSJ S MARY KISSEL NAILS IT ON THE DEM DEBA...,politics,"Nov 15, 2015",0
4,Lawmakers aim to delay U.S. ceding control of ...,WASHINGTON (Reuters) - Critics of a plan for t...,politicsNews,"September 13, 2016",1

In [6]:
df.tail()

,title,text,subject,date,label
5995,Exiled Venezuelan opposition magistrates resur...,SANTIAGO (Reuters) - A group of opposition-app...,worldnews,"October 19, 2017",1
5996,Plague outbreak in Madagascar kills 20: WHO,NAIROBI (Reuters) - An outbreak of plague has ...,worldnews,"September 29, 2017",1
5997,"Trump to visit Asia in November, North Korea i...",WASHINGTON (Reuters) - Donald Trump will trave...,worldnews,"September 29, 2017",1
5998,Melania Trump calls taped comments by Donald T...,(Reuters) - Melania Trump rose to her husband’...,politicsNews,"October 18, 2016",1
5999,"#BoycottPenzeys: HATEFUL, DIVISIVE Penzeys Spi...","Bill Penzey, the owner of Penzeys Spices, wrot...",politics,"Dec 2, 2016",0

In [7]:
df.isnull().sum()

title      0
text       0
subject    0
date       0
label      0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(5)

In [9]:
df.drop_duplicates(inplace=True)
df.shape

(5995, 5)

In [10]:
df.describe()

             label
count  5995.000000
mean      0.499583
std       0.500042
min       0.000000
25%       0.000000
50%       0.000000
75%       1.000000
max       1.000000

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5995 entries, 0 to 5999
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    5995 non-null   object
 1   text     5995 non-null   object
 2   subject  5995 non-null   object
 3   date     5995 non-null   object
 4   label    5995 non-null   int64
dtypes: int64(1), object(4)
memory usage: 281.0+ KB

In [12]:
df.columns

Index(['title', 'text', 'subject', 'date', 'label'], dtype='object')

In [13]:
df.dtypes

title      object
text       object
subject    object
date       object
label       int64
dtype: object